### ISSUE TITLE
Future support

### ISSUE THREAD

**Issue by rmeske** [mramonlopez/cordova-plugin-file-downloader#1]
Hello,

I have been using this plugin on iOS and Android and am wondering if there are any plans to make it compatible for devices running Windows?

Ron

**Comment by mramonlopez** [comment]
Hi,

My company isn't focused on Windows devices. I do not have the resources to dedicate myself to it in my free time (I haven't any Window phone to test and I haven't booted my window for months). I'll be pleased if someone contribute to this project.

Sorry

**Comment by rmeske** [comment]
Hi, 
I can understand that.  I do appreciate how easy you made it to download and unzip with one call.  

Ron
